---
title: "Data 556 HW 2"
author: "Naomi Liftman"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r}
#loading the package that includes rv distributions
library(stats)
```
# 2a.Use simulations to numerically estimate mean & variance of A. 
```{r}
#setting a seed so its reproducible
set.seed(99)

nsims=10000
records = rep(0,nsims)

for(i in 1:nsims){
  radius <- runif(1, min = 0, max = 1)
  records[i] <- ((radius^2)*pi)
}

#expectation of the area (the area is the records)
e_a = sum(records)/nsims #1.048
var_a = var(records) #.8768
```

# 3a. Use simulations to gain understadning about the distribution of R. Numerically estimate the expected value of R and 1/R. 
```{r}
#set seed
set.seed(100)

nsims=10000
records_x = rep(0,nsims)
records_y = rep(0,nsims)
records_rati = rep(0,nsims)
one_r = rep(0,nsims)

for(i in 1:nsims){
  x <- runif(1, min = 0, max = 1)
  y = 1-x
  records_x[i] <- x
  records_y[i] <- y
  records_ratio[i] <- (x/y)
  one_r[i] <- (y/x)
}

e_r = sum(records_ratio)/10000 #9.0554
e_r_one = sum(one_r)/10000 #8.438

```

# 6b. Use R to calculate the Monte Carlo estimates of mean + SD of x-y.
```{r}
set.seed(100)

nsims=10000
records_x = rep(0,nsims)
records_y = rep(0,nsims)
records_ratio = rep(0, nsims)

for(i in 1:nsims){
  x <- rnorm(1, mean = 69.1, sd = 2.9)
  y <- rnorm(1, mean = 63.7, sd = 2.7)
  records_x[i] <- x
  records_y[i] <- y
  records_ratio[i] <- (x - y)
}

e_r = sum(records_ratio)/10000 # 5.396
sd <- sd(records_ratio) #3.942
```


