---
title: "final"
output: html_document
---
Libraries
```{r warning = FALSE, message = FALSE, error = FALSE}
#libraries
library(rio)
library(tidyverse)
library(ggplot2)
```
Cleaning 
```{r}
#load data 
salary <- import('/Users/naomiliftman/Desktop/MSDS/Data 557/Final Project/salary.txt')

#check if there are any na's
sum(is.na(as.matrix(salary)))
#there are 4 

#get the rows so we can have a look at them 
rows_with_na <- salary[apply(
  salary, 
  1, 
  function(x) any(is.na(x))
  ), ]
#we can see that there are 4 NAs in the 'Rank' Category
#three of these 4 cases refer to the same faculty member (ID-417)
#the other is again a male faculty member (ID-1574)

#removing the NAs
salary_removed <- salary %>% 
  drop_na()
```

Inflation 
```{r}
#year goes from 76 through 95
#turning everything into 2026 dollars
salary_inflation <- salary_removed %>% 
  mutate(inflated_salary = case_when(
      year == 76 ~ salary*5.70,
      year == 77 ~ salary*5.35,
      year == 78 ~ salary*4.97,
      year == 79 ~ salary*4.47,
      year == 80 ~ salary*3.93,
      year == 81 ~ salary*3.56,
      year == 82 ~ salary*3.36,
      year == 83 ~ salary*3.25,
      year == 84 ~ salary*3.12,
      year == 85 ~ salary*3.01,
      year == 86 ~ salary*2.96,
      year == 87 ~ salary*2.85,
      year == 88 ~ salary*2.74,
      year == 89 ~ salary*2.61,
      year == 90 ~ salary*2.48,
      year == 91 ~ salary*2.38,
      year == 92 ~ salary*2.31,
      year == 93 ~ salary*2.24,
      year == 94 ~ salary*2.19,
      year == 95 ~ salary*2.13
    ))


```

# Question 1 
```{r}
starting <- salary_removed %>% 
  filter(startyr == year)
starting %>% 
  count()
```

# Start year model & sex
```{r}
model1 <- lm(salary~sex, data = starting)
#qq plot for normality
plot(model1, 2)
#residual vs fitted values for constant variance
ggplot(model1, aes(x = .fitted, y = .resid)) +
  geom_point(position = "jitter")+
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") 
#first need to add the predictor to a new df
df_residuals <- data.frame(
  predictor = starting$sex,
  residuals = residuals(model1)
)
#residuals vs predictor for linearity
ggplot(df_residuals, aes(x = predictor, y = residuals)) +
  geom_point(position = "jitter")
```

# Start year model with everything

```{r}
model2 <- lm(salary ~ sex + field + deg + yrdeg + startyr, data = starting)
#qq plot for normality
plot(model2, 2)
#residual vs fitted values for constant variance
ggplot(model2, aes(x = .fitted, y = .resid)) +
  geom_point()+
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") 
#check residuals vs predictor for linearity 
plot(model2, 1)
```

# Start year model with sex, field, and start year 
```{r}
model3 <- lm(salary~ sex + field + startyr, data = starting)
#check for normality
plot(model3, 2)
#check for constant variance
ggplot(model3, aes(x = .fitted, y = .resid)) +
  geom_point()+
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") 
#check linearity
plot(model3, 1)
```

# Questions 2