---
title: "HW 3"
output: html_document
---

```{r message = FALSE, warning = FALSE, error = FALSE}
#load libraries
library(stats)
library(ggplot2)
library(DescTools)
```

# Mode function which will be used throught the HW.
```{r}
Mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}
```


# 1a. Let U follow Uniform(a,b) Use simulations to numerically estimate the median and the mode of U for a = 0 and b = 2. 

```{r}
#set seed
set.seed(99)

uniform_values = runif(100, min = 0, max = 2)

median(uniform_values)
Mode(uniform_values)
```
# 2a. Use R to numerically estimate the median and the mode of X~Expo(2)

```{r}
set.seed(99)

expo_values = rexp(100, rate = 2)

median(expo_values)
Mode(expo_values)
```

# 3a. Use R to numerically estimate all means and modes of X for n = 1,2,..10.

```{r}
set.seed(99)
mean(runif(1))
Mode(runif(1))
mean(runif(2))
Mode(runif(2))
mean(runif(3))
Mode(runif(3))
mean(runif(4))
Mode(runif(4))
mean(runif(5))
Mode(runif(5))
mean(runif(6))
Mode(runif(6))
mean(runif(7))
Mode(runif(7))
mean(runif(8))
Mode(runif(8))
mean(runif(9))
Mode(runif(9))
mean(runif(10))
Mode(runif(10))
```

# 6a. Let X and Y be iid ~Unif(0,1). Numerically estiamte the covariance of X+Y and X-Y.

```{r}
#we know covariance is E(XY) - E(X)E(Y)
set.seed(100)

x = runif(10000, min = 0, max =1)
y = runif(10000, min = 0, max =1)

cov(x+y,x-y) 
```



