---
title: "survey"
output: pdf_document
---

```{r warning = FALSE, error = FALSE, message = FALSE}
library(tidyverse)
library(rio)
library(ggplot2)
```

```{r}
survey <- import("surveyapr13.csv")
senate <- survey %>% 
  filter(Split == "Faculty Senate")
council <- survey %>% 
  filter(Split == "Faculty Council")
boff <- survey %>% 
  filter(Split == "Faculty Council,Faculty Senate")
```

# senate split
```{r}
#just getting the questions they will see
senate_q <- senate %>% 
  select(18:21, 51:64)

#rename them to work with easier
senate_num <- senate_q %>% 
  rename(communicate_agenda = 5,
         information = 6,
         respond_approp = 7,
         admin_support = 8,
         comphy_concerns = 9,
         valued_unit = 10,
         effort_approp = 11,
         meaningful_contr = 12,
         wellrun = 13,
         concerns = 14,
         likertcomment = 15,
         process_senate = 16,
         policy_senate = 17,
         feedback = 18)

#changing them to numeric (0-5) zero being strongly disagree
#five being strongly agree and 3 is the middle
senate_num[senate_num == "Strongly agree"] <- 5
senate_num[senate_num == "Somewhat agree"] <- 4
senate_num[senate_num == "Neither agree nor disagree"] <- 3
senate_num[senate_num == "Somewhat disagree"] <- 2
senate_num[senate_num == "Strongly Disagree"] <- 1

#change them to numeric
senate_num <- transform(senate_num, communicate_agenda = as.numeric(communicate_agenda),
          information = as.numeric(information),
          respond_approp = as.numeric(respond_approp),
          admin_support = as.numeric(admin_support),
          comphy_concerns = as.numeric(comphy_concerns),
          valued_unit = as.numeric(valued_unit),
          effort_approp = as.numeric(effort_approp),
          meaningful_contr = as.numeric(meaningful_contr),
          wellrun = as.numeric(wellrun),
          concerns = as.numeric(concerns))

#create an averages dataframe
averages <- senate_num %>%
  summarise(across(where(is.numeric), mean, na.rm = TRUE))
```

# graphs
```{r}
#graphs
#gender
ggplot(data = senate_num, aes(x = Gender)) +
  geom_bar() +
  theme_bw()

#track
ggplot(data = senate_num, aes(x = Appointment)) +
  geom_bar() +
  theme_bw()

#years
yearsorder <- c("1-3 years", "3-5 years", "5-10 years", "10+ years")
ggplot(data = senate_num, aes(x = Years)) +
  geom_bar() +
  theme_bw() +
  scale_x_discrete(limits = yearsorder) +
  labs(title = "Distribution of Years at the University for Senate Members", x = "Years at the University", y = "Count")
```

# Likert analysis
```{r}
f <- sapply(senate_num, summary)
f
```

```{r}
#communicate agenda based on the appointment 
ggplot(data = senate_num, aes(x = communicate_agenda, fill = Appointment)) +
  geom_bar(position = "dodge") +
  xlim(0.5, 5.5)

#information based on the appointment 
ggplot(data = senate_num, aes(x = information, fill = Appointment)) +
  geom_bar(position = "dodge") +
  xlim(0.5, 5.5)

ggplot(data = senate_num, aes(x = respond_approp, fill = Appointment)) +
  geom_bar(position = "dodge") +
  xlim(0.5, 5.5)

ggplot(data = senate_num, aes(x = admin_support, fill = Appointment)) +
  geom_bar(position = "dodge") +
  xlim(0.5, 5.5)

ggplot(data = senate_num, aes(x = comphy_concerns, fill = Appointment)) +
  geom_bar(position = "dodge") +
  xlim(0.5, 5.5)

ggplot(data = senate_num, aes(x = valued_unit, fill = Appointment)) +
  geom_bar(position = "dodge") +
  xlim(0.5, 5.5)

ggplot(data = senate_num, aes(x = effort_approp, fill = Appointment)) +
  geom_bar(position = "dodge") +
  xlim(0.5, 5.5)

ggplot(data = senate_num, aes(x = meaningful_contr, fill = Appointment)) +
  geom_bar(position = "dodge") +
  xlim(0.5, 5.5)

ggplot(data = senate_num, aes(x = wellrun, fill = Appointment)) +
  geom_bar(position = "dodge") +
  xlim(0.5, 5.5)

ggplot(data = senate_num, aes(x = concerns, fill = Appointment)) +
  geom_bar(position = "dodge") +
  xlim(0.5, 5.5)
```


```{r}
#just getting the questions they will see
council_q <- council %>% 
  select(Gender:Years, 65:79)

#rename the columns
council_q <- council_q %>% 
  rename(communicate_agenda = 5,
         information = 6,
         respond_approp = 7,
         admin_support = 8,
         comphy_concerns = 9,
         valued_unit = 10,
         effort_approp = 11,
         meaningful_contr = 12,
         wellrun = 13,
         concerns = 14,
         likertcomment = 15,
         process_senate = 16,
         policy_senate = 17,
         feedback = 18)

#changing them to numeric (0-5) zero being strongly disagree
#five being strongly agree and 3 is the middle
council_q[council_q == "Strongly agree"] <- 5
council_q[council_q == "Somewhat agree"] <- 4
council_q[council_q == "Neither agree nor disagree"] <- 3
council_q[council_q == "Somewhat disagree"] <- 2
council_q[council_q == "Strongly Disagree"] <- 1

#change them to numeric
council_num <- transform(council_q, communicate_agenda = as.numeric(communicate_agenda),
          information = as.numeric(information),
          respond_approp = as.numeric(respond_approp),
          admin_support = as.numeric(admin_support),
          comphy_concerns = as.numeric(comphy_concerns),
          valued_unit = as.numeric(valued_unit),
          effort_approp = as.numeric(effort_approp),
          meaningful_contr = as.numeric(meaningful_contr),
          wellrun = as.numeric(wellrun),
          concerns = as.numeric(concerns))

averages_council <- data.frame(colMeans(council_num[, 5:14]))
```






